language: node_js
sudo: false
node_js:
  - "0.10"
before_script:
  - npm install istanbul coveralls
script:
  - istanbul cover ./tests/index.js
  - istanbul check-coverage --statement -100 --branch -100 --function 100 --lines 100
after_success:
  - coveralls < coverage/lcov.info

